Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,6 +24,7 @@ jobs:
         # 定义输出Markdown文件
         OUTPUT_FILE="README.md"
 
+        echo "Downloading RSS feed..."
         # 使用curl下载RSS XML文件内容
         rss_content=$(curl -s "https://blog.yangfei.site/feed/")
 
@@ -33,6 +34,7 @@ jobs:
           exit 1
         fi
 
+        echo "Parsing RSS feed..."
         # 使用xmlstarlet解析XML并提取文章标题、链接地址、发布时间
         titles=$(echo "$rss_content" | xmlstarlet sel -t -m "//item/title" -v . -n)
         links=$(echo "$rss_content" | xmlstarlet sel -t -m "//item/link" -v . -n)
@@ -44,6 +46,7 @@ jobs:
           exit 1
         fi
 
+        echo "Preparing content for README.md..."
         # 将提取内容按行分割并放入数组中
         IFS=$'\n' read -rd '' -a title_array <<<"$titles"
         IFS=$'\n' read -rd '' -a link_array <<<"$links"
@@ -56,7 +59,7 @@ jobs:
         # 将内容格式化并写入输出文件
         for i in "${!title_array[@]}"; do
           # 将日期格式化为[Y-m-d]
-          formatted_date=$(date -d "${date_array[$i]}" +"[%Y-%m-%d]")
+          formatted_date=$(date -d "${date_array[$i]}" +"[%Y-%m-%d]" || echo "Invalid Date")
           echo "$formatted_date - [${title_array[$i]}](${link_array[$i]})" >> "$OUTPUT_FILE"
         done
 
@@ -67,9 +70,9 @@ jobs:
         git config --global user.name "geekip"
 
         if [ -n "$(git status --porcelain)" ]; then
+          echo "Changes detected, committing to repository..."
           git add README.md
           git commit -m "Update README with latest blog posts"
           git push
         else
           echo "No changes to commit."
-        fi
